# Sample values
resource_group_name         = "rg-cis-benchmark"
location                    = "swedencentral"
project_name                = "cisportal"
environment                 = "dev"
owner                       = "platform-security"
app_service_plan_sku        = "FC1"
storage_account_tier        = "Standard"
storage_account_replication = "LRS"
