name: 'azurePolicyTerraform'

on:
  pull_request:
  push:
      branches:
          - main

permissions:
  contents: read
  id-token: write
  
jobs:
  terraform:
    name: 'azurePolicyTerraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
        TF_LOG: "DEBUG"
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        BACKEND_RG: ${{ secrets.RESOURCE_GROUP}}
        BACKEND_SG: ${{ secrets.STORAGE_ACCOUNT}}
        BACKEND_CONTAINER: ${{ secrets.CONTAINER_NAME}}
        BACKEND_KEY: ${{ secrets.BACKEND_KEY}}

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: Terraform version
        id: version
        run: terraform --version
        
      - name: Terraform env
        id: printenv
        run: printenv

      - name: 'Terraform Init'
        id: init
        run: |
          terraform init \
            -backend-config="use_oidc=$ARM_USE_OIDC" \
            -backend-config="resource_group_name=$BACKEND_RG" \
            -backend-config="storage_account_name=$BACKEND_SG" \
            -backend-config="container_name=$BACKEND_CONTAINER" \
            -backend-config="key=$BACKEND_KEY" \
            -backend-config="use_azuread_auth=$ARM_USE_AAD_AUTH" \
            -reconfigure
        env:
          ARM_USE_OIDC: true
          ARM_USE_AAD_AUTH: true
          TF_LOG_PATH: "terraform_oidc.log"
      - name: Upload the oidc debug log
        uses: actions/upload-artifact@v4
        with:
          name: tf-debug-oidc-log
          path: "/terraform-oidc.log"
      
      - name: Terraform Plan oidc
        id: plan
        run: |
          terraform plan \
            -no-color -out=out.tfplan
        env:
          ARM_USE_OIDC: true
          TF_LOG_PATH: "terraform-plan-oidc.log"

      - name: Upload the plan oidc debug log
        uses: actions/upload-artifact@v4
        with:
          name: tf-debug-plan-oidc-log
          path: "/terraform-oidc.log"
    
      - name: Upload the plan
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-oidc
          path: "/out.tfplan.log"


      - name: 'Terraform Apply'
        id: apply
        run: terraform apply -auto-approve out.tfplan 


        
        