name: 'azurePolicyTerraform'

on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: read
    id-token: write
  
jobs:
    terraform:
        name: 'azurePolicyTerraform'
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            - name: 'Checkout'
              uses: actions/checkout@v4
            - name: 'Setup Terraform'
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.8.2
            - name: 'Terraform Init'
              id: init
              run: terraform init -backend-config="resource_group_name=$RESOURCE_GROUP" -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME"
            - name: 'Terraform Plan'
              id: plan
              run: terraform plan
            - name: 'Terraform Apply'
              id: apply
              run: terraform apply -auto-approve  


        
        